name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Lint code
      run: |
        pip install flake8
        flake8 .

    - name: Build Docker image
      run: |
        docker build -t iris-ml-api .

    - name: Login and Push to Docker Hub
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin
        docker tag iris-ml-api $DOCKER_USER/iris-ml-api:latest
        docker push $DOCKER_USER/iris-ml-api:latest
